### ISSUE TITLE
io.paperdb.PaperDbException

### ISSUE THREAD

**Issue by MohNage7** [pilgr/Paper#102]
i got io.paperdb.PaperDbException in crash reports and it has been repeated 204 time with 38 users 

here's the crash log 

io.paperdb.PaperDbException: 
  at io.paperdb.DbStoragePlainFile.readTableFile (DbStoragePlainFile.java:266)
  at io.paperdb.DbStoragePlainFile.select (DbStoragePlainFile.java:151)
  at io.paperdb.Book.read (Book.java:68)
  at com.zadtec.zadfresh.utils.Helper.getMainCart (Helper.java:82)
  at com.zadtec.zadfresh.products.commons.ProductsAdapter.getShoppingCart (ProductsAdapter.java:92)
  at com.zadtec.zadfresh.products.commons.ProductsAdapter.<init> (ProductsAdapter.java:65)
  at com.zadtec.zadfresh.products.display.view.ProductsHomeFragment.setupRecycler (ProductsHomeFragment.java:120)
  at com.zadtec.zadfresh.products.display.view.ProductsHomeFragment.onCreateView (ProductsHomeFragment.java:109)
  at android.support.v4.app.Fragment.performCreateView (Fragment.java:2354)
  at android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1419)
  at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState (FragmentManager.java:1740)
  at android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1809)
  at android.support.v4.app.BackStackRecord.executeOps (BackStackRecord.java:799)
  at android.support.v4.app.FragmentManagerImpl.executeOps (FragmentManager.java:2580)
  at android.support.v4.app.FragmentManagerImpl.executeOpsTogether (FragmentManager.java:2367)
  at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute (FragmentManager.java:2322)
  at android.support.v4.app.FragmentManagerImpl.execPendingActions (FragmentManager.java:2229)
  at android.support.v4.app.FragmentManagerImpl$1.run (FragmentManager.java:700)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6682)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)

**Comment by rdoubleui** [comment]
@MohNage7 What android version are these reports from?

**Comment by pilgr** [comment]
@MohNage7 you should also have a nested exception pointing out to the root cause, do you have it? Like full stack trace.

**Comment by MohNage7** [comment]
@rdoubleui  @pilgr  unfortunately those reports from google play reports. 
Paper version : 2.5 
Android version : not specific version . but for example Android 5.1 , 6 , 7

**Comment by MohNage7** [comment]
i was able to pull this logs : 
FATAL EXCEPTION: main
                                                                       Process: com.zadfresh.zadfresh, PID: 19162
                                                                       io.paperdb.PaperDbException: Couldn't read/deserialize file /data/data/com.zadfresh.zadfresh/files/io.paperdb/main_cart.pt for table main_cart
                                                                           at io.paperdb.DbStoragePlainFile.readTableFile(DbStoragePlainFile.java:266)
                                                                           at io.paperdb.DbStoragePlainFile.select(DbStoragePlainFile.java:151)
                                                                           at io.paperdb.Book.read(Book.java:68)
                                                                           at com.zadtec.zadfresh.utils.Helper.getMainCart(Helper.java:82)
                                                                           at com.zadtec.zadfresh.products.commons.ProductsAdapter.getShoppingCart(ProductsAdapter.java:92)
                                                                           at com.zadtec.zadfresh.products.commons.ProductsAdapter.<init>(ProductsAdapter.java:65)
                                                                           at com.zadtec.zadfresh.products.display.view.ProductsHomeFragment.setupRecycler(ProductsHomeFragment.java:120)
                                                                           at com.zadtec.zadfresh.products.display.view.ProductsHomeFragment.onCreateView(ProductsHomeFragment.java:109)
                                                                           at android.support.v4.app.Fragment.performCreateView(Fragment.java:2354)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
                                                                           at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
                                                                           at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
                                                                           at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
                                                                           at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                                                                           at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
                                                                           at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:145)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7007)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
                                                                        Caused by: com.esotericsoftware.kryo.KryoException: Buffer underflow.
                                                                       Serialization trace:
                                                                       productNotes (com.zadtec.zadfresh.model.Pivot)
                                                                       pivot (com.zadtec.zadfresh.model.Product)
                                                                       product (com.zadtec.zadfresh.model.CartItem)
                                                                       itemsHashMap (com.zadtec.zadfresh.model.Cart)
                                                                       mContent (io.paperdb.PaperTable)
                                                                           at com.esotericsoftware.kryo.io.Input.require(Input.java:199)
                                                                           at com.esotericsoftware.kryo.io.Input.readUtf8_slow(Input.java:560)
                                                                           at com.esotericsoftware.kryo.io.Input.readUtf8(Input.java:553)
                                                                           at com.esotericsoftware.kryo.io.Input.readString(Input.java:483)
                                                                           at com.esotericsoftware.kryo.serializers.DefaultSerializers$StringSerializer.read(DefaultSerializers.java:199)
                                                                           at com.esotericsoftware.kryo.serializers.DefaultSerializers$StringSerializer.read(DefaultSerializers.java:188)
                                                                           at com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:789)
                                                                           at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:132)
                                                                           at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:145)
                                                                           at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:734)
                                                                           at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
                                                                           at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:145)
                                                                           at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:734)
                                                                           at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
                                                                           at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:145)
                                                                           at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:816)
                                                                           at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:161)
                                                                           at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:39)
                                                                       	at com.esotericsoftware.kryo.Kryo.readObj

**Comment by pilgr** [comment]
Thanks for the clarification, this is a known rare happening issue #4. I'm closing this one as a duplicate.

**Comment by pilgr** [comment]
if you at any time would reproduce it - please let me know

**Comment by SilkSama** [comment]
Hi I have the same issue (io.paperdb.PaperDbException: Couldn't read/deserialize file ) on Nexus 5X and only if I target SDK 26. I have tried on an other device not running SDK 26 and everything seems to be ok even if I target SDK 26.

**Comment by pilgr** [comment]
@SilkSama please make sure you use the latest Paper version and check `objenesis` lib version along transitive dependencies.

**Comment by SilkSama** [comment]
Hi @pilgr, you are right, I have updated Paper to the 2.6 but I have kept objenesis to the 2.2 version (I have forced objenesis to this version when I used the 2.0 version of Paper because of a conflict version with mockito). With the 2.5.1 version of objenesis everything is ok.
Thank you for your help :)

**Comment by asim019** [comment]
@pilgr Hi,
I am using this library in one of my project and its working fine on all available devices but in emulator with Oreo(api 26) this issue is always producible.

**Comment by pilgr** [comment]
@asim019 please make sure you are using the latest paper version. Also please run gradle dependency command to check out the version of objenesis lib.

**Comment by asim019** [comment]
@pilgr Hi,
Thanks for your response. Updating paper version has resolved the issue.
