### ISSUE TITLE
Structure changes cause crashes

### ISSUE THREAD

**Issue by MurtadhaS** [pilgr/Paper#107]
Hi,

I have a data model objects stored in PaperDB. However, when I try to restore that data after changing the model, a crash happens telling me that it couldn't _de-serialize_ the data.
Is that the normal expected attitude?
Can I have a quick fix for this?

**Comment by pilgr** [comment]
Hi, 

it's not expected. Please provide more information:
- the class structure before and after changes.
- the stack trace
- the version of the lib

**Comment by MarkNjunge** [comment]
Hi, 
I'm also encountering the same issue. It seems to happen when changing the data type of a field as opposed to removing/adding a field.

I'm using version 2.6

**Before**
``` Kotlin
data class TrackerIdData(
	val trackerId: String,
	val temperature: Int,
	val current: Int,
	val oilLevel: Int,
	val latitude: Long,
	val longitude: Long,
	val timestamp: Int
)
```

**After**
``` Kotlin
data class TrackerIdData(
	val trackerId: String,
	val temperature: Double,
	val current: Double,
	val oilLevel: Double,
	val latitude: Double,
	val longitude: Double,
	val timestamp: Long
)
```

**Stracktrace**
```
                                                                     Caused by: io.paperdb.PaperDbException: Couldn't read/deserialize file /data/user/0/com.marknkamau.gms/files/io.paperdb/lastValue.pt for table lastValue
                                                                        at io.paperdb.DbStoragePlainFile.readTableFile(DbStoragePlainFile.java:298)
                                                                        at io.paperdb.DbStoragePlainFile.select(DbStoragePlainFile.java:158)
                                                                        at io.paperdb.Book.read(Book.java:73)
                                                                        at io.paperdb.Book.read(Book.java:58)
                                                                        at com.marknkamau.gms.data.local.paper.PaperServiceData.getLastValue(PaperServiceData.kt:37)
                                                                        at com.marknkamau.gms.ui.trackerid.TrackerIdPresenter.<init>(TrackerIdPresenter.kt:50)
                                                                        at com.marknkamau.gms.ui.trackerid.TrackerIdActivity.onCreate(TrackerIdActivity.kt:39)
                                                                        at android.app.Activity.performCreate(Activity.java:6999)
                                                                        at android.app.Activity.performCreate(Activity.java:6990)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
                                                                        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                        at android.os.Looper.loop(Looper.java:164) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6494) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
                                                                     Caused by: com.esotericsoftware.kryo.KryoException: com.esotericsoftware.kryo.KryoException: Buffer underflow.
                                                                    Serialization trace:
                                                                    current (com.marknkamau.gms.data.models.TrackerIdData)
                                                                    mContent (io.paperdb.PaperTable)
                                                                        at com.esotericsoftware.kryo.serializers.ObjectField$ObjectDoubleField.read(ObjectField.java:487)
                                                                        at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:145)
                                                                        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:734)
                                                                        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
                                                                        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:543)
                                                                        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:712)
                                                                        at io.paperdb.DbStoragePlainFile.readContent(DbStoragePlainFile.java:307)
                                                                        at io.paperdb.DbStoragePlainFile.readTableFile(DbStoragePlainFile.java:291)
                                                                        	... 19 more
                                                                     Caused by: com.esotericsoftware.kryo.KryoException: Buffer underflow.
                                                                        at com.esotericsoftware.kryo.io.Input.require(Input.java:199)
                                                                        at com.esotericsoftware.kryo.io.Input.readLong(Input.java:686)
                                                                        at com.esotericsoftware.kryo.io.Input.readDouble(Input.java:817)
                                                                        at com.esotericsoftware.kryo.serializers.ObjectField$ObjectDoubleField.read(ObjectField.java:485)
                                                                        	... 26 more
```

**Comment by pilgr** [comment]
Yep, field type changes are not supported. Added a note to the readme
https://github.com/pilgr/Paper/blob/master/README.md#handle-data-structure-changes

**Comment by pilgr** [comment]
If you need to change field data type you can :
* remove old data to avoid reading old class structure (if data are not critical)
* change field name along with the type. That new field will have its default value. And the field with old name will be ignored.
