### ISSUE TITLE
Paper trapped in recursive calls

### ISSUE THREAD

**Issue by albertdatui** [pilgr/Paper#11]
Hi guys, is there anybody who can help me with this error?
I suspect it is trapped in recursive calls. any idea how to fix this?

```
07-14 00:03:44.102  24180-24180/com.application.android.myapplication E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.application.android.myapplication, PID: 24180
    java.lang.StackOverflowError
            at com.esotericsoftware.kryo.io.Output.flush(Output.java:181)
            at com.esotericsoftware.kryo.io.Output.require(Output.java:160)
            at com.esotericsoftware.kryo.io.Output.writeBytes(Output.java:246)
            at com.esotericsoftware.kryo.io.Output.write(Output.java:214)
            at com.esotericsoftware.kryo.io.Output.flush(Output.java:181)
            at com.esotericsoftware.kryo.io.OutputChunked.flush(OutputChunked.java:63)
            at com.esotericsoftware.kryo.io.Output.require(Output.java:160)
            at com.esotericsoftware.kryo.io.Output.writeBytes(Output.java:246)
            at com.esotericsoftware.kryo.io.Output.write(Output.java:214)
            at com.esotericsoftware.kryo.io.Output.flush(Output.java:181)
            at com.esotericsoftware.kryo.io.OutputChunked.flush(OutputChunked.java:63)
            at com.esotericsoftware.kryo.io.Output.require(Output.java:160)
            at com.esotericsoftware.kryo.io.Output.writeBytes(Output.java:246)
            at com.esotericsoftware.kryo.io.Output.write(Output.java:214)
            at com.esotericsoftware.kryo.io.Output.flush(Output.java:181)
            at com.esotericsoftware.kryo.io.OutputChunked.flush(OutputChunked.java:63)
            at com.esotericsoftware.kryo.io.Output.require(Output.java:160)
            at com.esotericsoftware.kryo.io.Output.writeBytes(Output.java:246)
            at com.esotericsoftware.kryo.io.Output.write(Output.java:214)
            at com.esotericsoftware.kryo.io.Output.flush(Output.java:181)
            at com.esotericsoftware.kryo.io.OutputChunked.flush(OutputChunked.java:63)
            at com.esotericsoftware.kryo.io.Output.require(Output.java:160)
            at com.esotericsoftware.kryo.io.Output.writeBytes(Output.java:246)
            at com.esotericsoftware.kryo.io.Output.write(Output.java:214)
            at com.esotericsoftware.kryo.io.Output.flush(Output.java:181)
            at com.esotericsoftware.kryo.io.OutputChunked.flush(OutputChunked.java:63)
            at com.esotericsoftware.kryo.io.Output.require(Output.java:160)
            at com.esotericsoftware.kryo.io.Output.writeBytes(Output.java:246)
            at com.esotericsoftware.kryo.io.Output.write(Output.java:214)
            at com.esotericsoftware.kryo.io.Output.flush(Output.java:181)
            at com.esotericsoftware.kryo.io.OutputChunked.flush(OutputChunked.java:63)
            at com.esotericsoftware.kryo.io.Output.require(Output.java:160)
            at com.esotericsoftware.kryo.io.Output.writeBytes(Output.java:246)
            at com.esotericsoftware.kryo.io.Output.write(Output.java:214)
            at com.esotericsoftware.kryo.io.Output.flush(Output.java:181)
            at com.esotericsoftware.kryo.io.OutputChunked.flush(OutputChunked.java:63)
            at com.esotericsoftware.kryo.io.Output.require(Output.java:160)
            at com.esotericsoftware.kryo.io.Output.writeBytes(Output.java:246)
            at com.esotericsoftware.kryo.io.Output.write(Output.java:214)
            at com.esotericsoftware.kryo.io.Output.flush(Output.java:181)
            at com.esotericsoftware.kryo.io.OutputChunked.flush(OutputChunked.java:63)
            at com.esotericsoftware.kryo.io.Output.require(Output.java:160)
            at com.esotericsoftware.kryo.io.Output.writeBytes(Output.java:246)
            at com.esotericsoftware.kryo.io.Output.write(Output.java:214)
            at com.esotericsoftware.kryo.io.Output.flush(Output.java:181)
            at com.esotericsoftware.kryo.io.OutputChunked.flush(OutputChunked.java:63)
            at com.esotericsoftware.kryo.io.Output.require(Output.java:160)
            at com.esotericsoftware.kryo.io.Output.writeBytes(Output.java:246)
            at com.esotericsoftware.kryo.io.Output.write(Output.java:214)
            at com.esotericsoftware.kryo.io.Output.flush(Output.java:181)
            at com.esotericsoftware.kryo.io.OutputChunked.flush(OutputChunked.java:63)
            at com.esotericsoftware.kryo.io.Output.require(Output.java:160)
            at com.esotericsoftware.kryo.io.Output.writeBytes(Output.java:246)
            at com.esotericsoftware.kryo.io.Output.write(Output.java:214)
            at com.esotericsoftware.kryo.io.Output.flush(Output.java:181)
            at com.esotericsoftware.kryo.io.OutputChunked.flush(OutputChunked.java:63)
            at com.esotericsoftware.kryo.io.Output.require(Output.java:160)
            at com.esotericsoftware.kryo.io.Output.writeBytes(Output.java:246)
            at com.esotericsoftware.kryo.io.Output.write(Output.java:214)
    at
```

**Comment by pilgr** [comment]
Make sure your object graph doesn't have cyclic dependencies. Also you can exclude fields which cause such error using _transient_.

**Comment by pilgr** [comment]
Have you had an cyclic dependencies which are not supported by Paper? Can we close the issue then?

**Comment by albertdatui** [comment]
hi..
I am not sure whether the object has cyclic dependencies because I am trying to save Resource object in android. Any Idea?

**Comment by pilgr** [comment]
Resource is an system runtime object, definitely it may contain cyclic dependencies. You shouldn't use Paper to save Context, Resources, PendingIntent and other system runtime objects. Paper purpose is to save your data objects. If you have reference to Resource in saved classes (which is looks bad) you can avoid saving them using _transient_ fields.
