### ISSUE TITLE
io.paperdb.PaperDbException: Couldn't read/deserialize file 

### ISSUE THREAD

**Issue by siddhpuraamitr** [pilgr/Paper#117]
I am passing view to Paper by below code

       ```
linearLayout = (LinearLayout)findViewById(R.id.llMainLayout);
        View view1 = Paper.book().read("llMain");
        if(view1 != null) {

            View view = (View) linearLayout;
            Paper.book().write("llMain", view);
        }
        linearLayout.addView(view1);
```
```
But I am getting below error
```
 Caused by: io.paperdb.PaperDbException: Couldn't read/deserialize file /data/user/0/com.example.amitsiddhpura.paperview/files/io.paperdb/llMain.pt for table llMain
                                                                                         at io.paperdb.DbStoragePlainFile.readTableFile(DbStoragePlainFile.java:298)
                                                                                         at io.paperdb.DbStoragePlainFile.select(DbStoragePlainFile.java:158)
                                                                                         at io.paperdb.Book.read(Book.java:73)
                                                                                         at io.paperdb.Book.read(Book.java:58)
                                                                                         at com.example.amitsiddhpura.paperview.MainActivity.onCreate(MainActivity.java:18)
                                                                                         at android.app.Activity.performCreate(Activity.java:6999)
                                                                                         at android.app.Activity.performCreate(Activity.java:6990)
                                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
                                                                                         at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                         at android.os.Looper.loop(Looper.java:164) 
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:6494) 
```

**Comment by pilgr** [comment]
May I ask you what is the reason to save a view? :) You can't serialize and save a View instance. It has a reference to the runtime Context object.

**Comment by fahadtaric** [comment]
I am getting the same error even if not saving a view. 

   if(!Paper.book().exist(PaperUtils.Art) ||Paper.book().read(PaperUtils.Art,new ArrayList<Art>()).size()<=0)) {
           readArt(context);
        }

**Comment by adnanakbar425** [comment]
getting sam error dont know how to fix this.
if(Paper.book().read("orders")!=null) {
            ordersArrayList = Paper.book().read("orders");
        }

**Comment by jamesced445** [comment]
hey guix is there a solution on this io.paper db is erorr upon minify enable true.
