### ISSUE TITLE
Error reading object with Bitmap inside

### ISSUE THREAD

**Issue by dolphinziyo** [pilgr/Paper#20]
I get an error when reading an object with a Bitmap field, the error thrown is:
*"You have to add a public no-arg constructor for the class android.graphics.Bitmap"
The StackTrace: 
    mContent (io.paperdb.PaperTable)
    Read more: https://github.com/pilgr/Paper#save
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2936)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2965)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1406)
            at android.os.Handler.dispatchMessage(Handler.java:107)
            at android.os.Looper.loop(Looper.java:194)
            at android.app.ActivityThread.main(ActivityThread.java:5371)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: io.paperdb.PaperDbException: You have to add a public no-arg constructor for the class android.graphics.Bitmap

I can't add a constructor to the Bitmap class

**Comment by pilgr** [comment]
You can try out the latest Paper version. It doesn't require no-arg constructors for saved classed now.
