### ISSUE TITLE
Crash: Class cannot be created (non-static member class)

### ISSUE THREAD

**Issue by Uphie** [pilgr/Paper#34]
My class contains an inner class ，shows below:

	public class Question {
	    public QNCmt entQNCmt;
	    public String strLastUpdateDate;
	    public String strDayDiffer;
	    public String sWebLk;
	    public int strPraiseNumber;
	    public int strQuestionId;
	    public String strQuestionTitle;
	    public String strQuestionContent;
	    public String strAnswerTitle;
	    public String strAnswerContent;
	    public String strQuestionMarketTime;
	    public String sEditor;
	
	    public class QNCmt {
	        public String strCnt;
	        public String strId;
	        public String strD;
	        public String pNum;
	        public String upFg;
	    }
	}

When restoring local data to this class ,it crashes. 

     Caused by: com.esotericsoftware.kryo.KryoException: Class cannot be created (non-static member class): studio.uphie.one.ui.question.Question$QNCmt
                                                                  Serialization trace:
                                                                  entQNCmt (studio.uphie.one.ui.question.Question)
                                                                  mContent (io.paperdb.PaperTable)
                                                                      at com.esotericsoftware.kryo.Kryo$DefaultInstantiatorStrategy.newInstantiatorOf(Kryo.java:1267)
                                                                      at com.esotericsoftware.kryo.Kryo.newInstantiator(Kryo.java:1075)
                                                                      at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1084)
                                                                      at com.esotericsoftware.kryo.serializers.FieldSerializer.create(FieldSerializer.java:570)
                                                                      at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:68)
                                                                      at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708)
                                                                      at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
                                                                      at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:110)
                                                                      at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708)
                                                                      at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
                                                                      at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
                                                                      at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:686)
                                                                      at io.paperdb.DbStoragePlainFile.readTableFile(DbStoragePlainFile.java:222)
                                                                      	... 29 more

Doesn't paper support classes with inner classes in ?

And, I have a suggestion that paper adds a data-expire function :)

**Comment by pilgr** [comment]
Your inner class must be static `public static class QNCmt`. 
You can add any additional field to your data classes to trace expire period. Or make a base data class with such fields and helper methods to check expiration date. Such features are out of Paper's scope.

**Comment by Uphie** [comment]
Yes, it works. I'm thinking about that a static inner class may be limited in some situations, which may be in confict with something. Well , I need to read you code seriously :)
Thanks!
