### ISSUE TITLE
File not found exception while saving table

### ISSUE THREAD

**Issue by FranciscoE-Hudl** [pilgr/Paper#43]
The use case is quite simple: save a value to the database. The saving process works most of the time, but it's not consistent. I do have permissions for READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE.

I believe this may be a device-specific issue. The device is a Samsung Samsung Galaxy Tab S2 9.7 (SM-T810).

```
05-16 06:37:39.383 31449-31977/com.my.app W/System.err:   io.paperdb.PaperDbException: Couldn't save table: my_table. Backed up table will be used on next read attempt
05-16 06:37:39.383 31449-31977/com.my.app W/System.err:     at io.paperdb.DbStoragePlainFile.writeTableFile(DbStoragePlainFile.java:229)
05-16 06:37:39.383 31449-31977/com.my.app W/System.err:     at io.paperdb.DbStoragePlainFile.insert(DbStoragePlainFile.java:127)
05-16 06:37:39.383 31449-31977/com.my.app W/System.err:     at io.paperdb.Book.write(Book.java:36)
05-16 06:37:39.383 31449-31977/com.my.app W/System.err:     at com.pacoworks.rxpaper.RxPaperBook$1.call(RxPaperBook.java:155)
05-16 06:37:39.383 31449-31977/com.my.app W/System.err:     at rx.Completable$8.call(Completable.java:487)
05-16 06:37:39.383 31449-31977/com.my.app W/System.err:     at rx.Completable$8.call(Completable.java:481)
05-16 06:37:39.383 31449-31977/com.my.app W/System.err:     at rx.Completable.subscribe(Completable.java:1970)
05-16 06:37:39.383 31449-31977/com.my.app W/System.err:     at rx.Completable$29$1.call(Completable.java:2041)
05-16 06:37:39.383 31449-31977/com.my.app W/System.err:     at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:222)
05-16 06:37:39.383 31449-31977/com.my.app W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
05-16 06:37:39.383 31449-31977/com.my.app W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
05-16 06:37:39.383 31449-31977/com.my.app W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-16 06:37:39.383 31449-31977/com.my.app W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
05-16 06:37:39.383 31449-31977/com.my.app W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
05-16 06:37:39.383 31449-31977/com.my.app W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
05-16 06:37:39.383 31449-31977/com.my.app W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at java.lang.Thread.run(Thread.java:818)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:   Caused by: java.io.FileNotFoundException: /data/data/com.my.app/files/highlights/athlete_highlights.pt: open failed: ENOENT (No such file or directory)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:456)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at io.paperdb.DbStoragePlainFile.writeTableFile(DbStoragePlainFile.java:209)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at io.paperdb.DbStoragePlainFile.insert(DbStoragePlainFile.java:127)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at io.paperdb.Book.write(Book.java:36)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at com.pacoworks.rxpaper.RxPaperBook$1.call(RxPaperBook.java:155)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at rx.Completable$8.call(Completable.java:487)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at rx.Completable$8.call(Completable.java:481)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at rx.Completable.subscribe(Completable.java:1970)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at rx.Completable$29$1.call(Completable.java:2041)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:222)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at java.lang.Thread.run(Thread.java:818)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:   Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at libcore.io.Posix.open(Native Method)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:442)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at io.paperdb.DbStoragePlainFile.writeTableFile(DbStoragePlainFile.java:209)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at io.paperdb.DbStoragePlainFile.insert(DbStoragePlainFile.java:127)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at io.paperdb.Book.write(Book.java:36)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at com.pacoworks.rxpaper.RxPaperBook$1.call(RxPaperBook.java:155)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at rx.Completable$8.call(Completable.java:487)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at rx.Completable$8.call(Completable.java:481)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at rx.Completable.subscribe(Completable.java:1970)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at rx.Completable$29$1.call(Completable.java:2041)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:222)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
05-16 06:37:39.388 31449-31977/com.my.app W/System.err:     at java.lang.Thread.run(Thread.java:818)
```

**Comment by pilgr** [comment]
Seems to be device has some problems with the storage.

**Comment by champrocks3190** [comment]
what you are saving the type of data im saving is byte when i m getting this error 

Backed up table will be used on next read attempt 

im using xperia z2 sony im also having same issue .

**Comment by rmirabelle** [comment]
Same issue - also with Samsung, Galaxy Tab Active Pro (SMT540). Intermittent.
