### ISSUE TITLE
 java.lang.OutOfMemoryError when reading an object from Paper.

### ISSUE THREAD

**Issue by makovkastar** [pilgr/Paper#59]
A user object saved in Paper was refactored (long ID field was replaced with String ID). Now when trying to read an object from Paper the following exception occurs:

```
java.lang.OutOfMemoryError
                      at com.esotericsoftware.kryo.io.Input.readString(Input.java:482)
                      at com.esotericsoftware.kryo.serializers.DefaultSerializers$StringSerializer.read(DefaultSerializers.java:195)
                      at com.esotericsoftware.kryo.serializers.DefaultSerializers$StringSerializer.read(DefaultSerializers.java:184)
                      at com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:763)
                      at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:132)
                      at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:110)
                      at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708)
                      at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
                      at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
                      at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:686)
                      at io.paperdb.DbStoragePlainFile.readTableFile(DbStoragePlainFile.java:239)
                      at io.paperdb.DbStoragePlainFile.select(DbStoragePlainFile.java:147)
                      at io.paperdb.Book.read(Book.java:67)
```

**Comment by pilgr** [comment]
Unfortunately, Paper supports only limited backward compatibility like adding or removing fields. Type change not supported.

**Comment by makovkastar** [comment]
Thank you for the fast reply. I will delete an object with the old structure and create one with the new then.

**Comment by pilgr** [comment]
Also you can just add one more id field to the existing class and mark old
one as 'transient'.
